### ISSUE TITLE
Vertaisarvostelu part 2

### ISSUE THREAD

**Issue by HYTApio** [matiasto/tsoha_poll_app#2]
Arvioitu 25.4 

Sovelluksen kirjautumisvalikko näyttää hyvältä. Virhekoodit voisi olla hyvä lisä kirjautumisen epäonnistumiselle sekä sign upin epäonnistumiselle. Esimerkiksi kun yritin luoda pitkällä käyttäjänimellä niin ei onnistunut. Mikä on jo hyvä niin, mutta jos saisi esim viestin että käyttäjänimi on liian pitkä tms. 

Sitten kirjautuneena Home. Sovellksen ulkoasu on hyvin toteutettu ja siisti. Ensimmäisenä silmään pisti create a poll ja profile valikon painikkeen valkoisuus (ei näe mitä lukee), mutta kun on kerran käynyt niissä niin ne muuttuvat liloiksi.  Kyselyt tulevat hyvin näkyville ja info vasemmalla puolella on kiva. 

Profile: Deactivate ja reactivate toimii hyvin ja selkeästi. Review toimii hyvin, mutta käyttäjä ei voi muokata omia arvostelujaan. Käyttäjä voi myös arvostella oman kyselynsä, joka tietenkin on joissain tapauksissa hyvä. Arvostelun ulkoasu on todella selkeä ja ymmärrettävä.

Create a poll: Hyvin toimiva alusta joka on selkä. Voisi olla taas error viestit jos esimerkiksi header on liian pitkä statementissä. Uuden statementin lisäämisessä missing header on kiva lisä jolloin ei voi lisätä tyhjää statementtiä. Samoin se, että pitää olla vähintään 1 statement ennen lisäystä.

Oikeuksia: Jollei ole kirjautunut ei pääse näkemään mitään asioita mitä ei pitäisi nähdä. Ei pääse näkemään piilotettuja kyselyitä muokkaamalla osoitetta. Hyvä. Valkoisen ruudum sijaan käyttäjän voisi ohjata esimerkiksi takaisin home sivulle tai kirjautumisvalikkoon. 

Koodi oli siistiä (sen mitä itse ymmärsin, koska java ei ole tuttua). 

Hyvällä mallilla sovellus ylipäätään ja kuten huomioita sovelluksen käyttämisestä sanotaan: viesteille on jo hyvä pohja niin ne vielä mukaan niin alkaa olla todella hyvä käyttökokemus.

**Comment by matiasto** [comment]
Kiitos hyvästä palautteesta. Erinomaisia ehdotuksia joista otan varmasti koppia.

Hyvää kevään jatkoa.
